### ISSUE TITLE
Rewrite in C++/Felix/something better

### ISSUE THREAD

**Issue by refi64** [kirbyfan64/unmangler#4]
My brilliant idea of using C (I have _no_ clue why the heck I did that) is stupid because:
- C++ is needed anyway (who installs `libstdc++` or `libc++` without a C++ compiler?)
- #3 would have been solved by now. 20 times.

Felix uses the RE2 regex library. It does not work on Windows, however.

C++11 may be the best option.

Any opinion from all 1 people watching this repo?

**Comment by phase** [comment]
C++14? 11 would be good for compatibility, but 14's got a lot of cool features. I'd stay up to date and use 14.

**Comment by refi64** [comment]
@phase I'm not sure if C++14 would make a difference. I don't think any of the new features would really end up being used...

**Comment by phase** [comment]
@kirbyfan64 C++11 it is!

**Comment by refi64** [comment]
@phase Wow, you didn't even consider Felix, did you?? :O

I guess it's C++12 then.

**Comment by refi64** [comment]
s/12/11/
